### ISSUE TITLE
Regarding Simulation version of codebase

### ISSUE THREAD

**Issue by hars-singh** [moka-manipulation/moka#1]
Hi, Thanks for the great work!

Is there any plan to release anything related to any simulation platform?

**Comment by FangchenLiu** [comment]
Hi, thank you for your interest in our work.
Currently, we may not consider releasing a version in simulation, as all our experiments are on real robots, and also VLM performs better on realistic objects and scenes.
However, you can try to integrate the robot-free prompting demo into your simulation suite to see how well it works 👍
